### ISSUE TITLE
Uncaught PDOException: There is no active transaction in /var/www/tt-rss/classes/rssutils.php:1176

### ISSUE THREAD

**Issue by dugite-code** [feediron/ttrss_plugin-feediron#78]
I've confirmed disabling FeedIron prevents this issue

```
PHP Fatal error:  Uncaught PDOException: There is no active transaction in /var/www/tt-rss/classes/rssutils.php:1176
Stack trace:
#0 /var/www/tt-rss/classes/rssutils.php(1176): PDO->commit()
#1 /var/www/tt-rss/update.php(415): RSSUtils::update_rss_feed('50')
#2 {main}
  thrown in /var/www/tt-rss/classes/rssutils.php on line 1176
```

## Context

* Operating System: Debian 9
* TTRSS version/git version: 26a89ab6
* PHP version: 7.0
* Feediron Configuration:

```json
{
        "type": "xpath",
        "xpath": "link[@rel='canonical']\/@href",
        "modify": [
            {
                "type": "replace",
                "search": [
                    "https:\/\/www.youtube.com\/watch?v="
                ],
                "replace": [
                    "<iframe width=\"640\" height=\"360\" src=\"https:\/\/www.youtube.com\/embed\/"
                ]
            }
        ],
        "end_element": "\"><\/iframe>"
    }
```

**Comment by dugite-code** [comment]
Using both a dimple "xpath":"div" and readability results in the same error

**Comment by dugite-code** [comment]
Well It seams if the src is empty this causes the issue. Might be solved with better error checking
